### ISSUE TITLE
Is hashing a (large) CSV introducing duplicates?

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/hashfields#24]
We have a CSV with just over 5K distinct rows.

When this CSV is hashed, we wind up with _more_ rows than we started with, with the extras being full duplicates of existing rows.

We should always output the exact same number of rows we input.

**Comment by angela-tran** [comment]
> When this CSV is hashed, we wind up with more rows than we started with, with the extras being full duplicates of existing rows.

We are also seeing that when we count the distinct records in the hashed output, it is less than the records in the original CSV. (5513 in the hashed, 5535 in the original)
